#!/bin/bash

#SBATCH --account=d403-wt
#SBATCH --job-name=microbenchmark
#SBATCH --time=8:00:00
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --exclusive


#SBATCH --output=MBresult/%x_%j.out

module load gcc
module load intel-license
module load intel-20.4/cc
module load intel-20.4/fc
module load intel-20.4/compilers 
module load mpt
module load nvidia/nvhpc
module load openmpi/4.1.6
module load python
# srun ompdev
# srun microbenchmark 1 2 
# srun microbenchmark 3 4
# srun microbenchmark 5 6
# srun microbenchmark 7 8
# srun microbenchmark 9 10
# srun microbenchmark 11 12
srun microbenchmark 7


